import { formatTestTitle, formatTestDescription } from '../src/utils/testLocalizationHelper.js';

console.log('--- RUNNING STEP 106: TEST TITLES & DESCRIPTIONS LOCALIZATION ---');

let passed = 0;
let total = 0;

function assert(condition, message) {
  total++;
  if (condition) {
    passed++;
    console.log(`  ✓ ${total}. ${message}`);
  } else {
    console.error(`  ✗ ${total}. ${message}`);
    process.exit(1);
  }
}

// 1. formatTestTitle
assert(
  formatTestTitle('✨ [AI Cộng Đồng] Next-Gen Perovskite Solar Cells', true) === '✨ [Community AI] Next-Gen Perovskite Solar Cells',
  'formatTestTitle converts [AI Cộng Đồng] to [Community AI] in English mode'
);

assert(
  formatTestTitle('✨ [AI Cộng Đồng] Next-Gen Perovskite Solar Cells', false) === '✨ [AI Cộng Đồng] Next-Gen Perovskite Solar Cells',
  'formatTestTitle preserves Vietnamese title in vi mode'
);

// 2. formatTestDescription for Cambridge 20 Reading
const cam20DescVi = 'Bộ đề thi thử IELTS Reading chuẩn khảo thí Cambridge 20 (Mới nhất) gồm đầy đủ 3 bài đọc học thuật với 40 câu hỏi, thời gian làm bài 60 phút.';
const cam20DescEn = formatTestDescription(cam20DescVi, true, { cambridgeBook: 20 });
assert(
  cam20DescEn.includes('Official Cambridge 20 IELTS Reading practice test (Latest)') && cam20DescEn.includes('40 questions') && cam20DescEn.includes('60-minute time limit'),
  'formatTestDescription translates Cambridge 20 Reading description accurately'
);

assert(
  formatTestDescription(cam20DescVi, false, { cambridgeBook: 20 }) === cam20DescVi,
  'formatTestDescription preserves original description when isEn is false'
);

// 3. formatTestDescription for Cambridge 18 Reading
const cam18DescVi = 'Bộ đề thi thử IELTS Reading chuẩn khảo thí Cambridge 18 gồm đầy đủ 3 bài đọc học thuật với 40 câu hỏi, thời gian làm bài 60 phút.';
const cam18DescEn = formatTestDescription(cam18DescVi, true, { cambridgeBook: 18 });
assert(
  cam18DescEn.includes('Official Cambridge 18 IELTS Reading practice test') && !cam18DescEn.includes('(Latest)'),
  'formatTestDescription translates Cambridge 18 Reading description accurately'
);

// 4. formatTestDescription for Cambridge 15 Reading
const cam15DescVi = 'Bộ đề thi thử chuẩn Cambridge Academic gồm 3 bài đọc với đầy đủ 40 câu hỏi, thời gian làm bài 60 phút.';
const cam15DescEn = formatTestDescription(cam15DescVi, true, { cambridgeBook: 15 });
assert(
  cam15DescEn.includes('Authentic Cambridge Academic practice test featuring 3 complete passages'),
  'formatTestDescription translates Cambridge 15 Reading description accurately'
);

// 5. formatTestDescription for AI Community test
const aiDescVi = 'Đề thi đọc học thuật do AI thiết kế chuẩn Cambridge Academic: Cơ chế pin mặt trời Perovskite, hiệu suất chuyển đổi quang năng và bài toán kinh tế.';
const aiDescEn = formatTestDescription(aiDescVi, true, {});
assert(
  aiDescEn.includes('Academic reading test generated by AI under Cambridge Academic standards') && aiDescEn.includes('Perovskite solar cell mechanics'),
  'formatTestDescription translates AI Community Perovskite description accurately'
);

// 6. formatTestDescription for Cambridge Listening
const camListDescVi = 'Bộ đề thi thử IELTS Listening chuẩn khảo thí Cambridge 20 (Mới nhất) gồm đầy đủ 4 phần (Part 1–4) với 40 câu hỏi, thời lượng audio 30 phút và 2 phút kiểm tra lại bài.';
const camListDescEn = formatTestDescription(camListDescVi, true, { cambridgeBook: 20 });
assert(
  camListDescEn.includes('Official Cambridge 20 IELTS Listening mock test (Latest)') && camListDescEn.includes('40 questions') && camListDescEn.includes('30-min audio'),
  'formatTestDescription translates Cambridge Listening description accurately'
);

// 7. formatTestDescription for Assembled test
const assembledVi = 'Bộ đề thi thử 3 Passages tự lắp ghép từ ngân hàng đề (Passage A + Passage B + Passage C). Chuẩn thi thật 60 phút.';
const assembledEn = formatTestDescription(assembledVi, true, {});
assert(
  assembledEn.includes('Custom 3-Passage mock exam assembled from the test bank (Passage A + Passage B + Passage C)') && assembledEn.includes('Cambridge 60-minute standard'),
  'formatTestDescription translates assembled test description accurately'
);

// 8. formatTestDescription for Gemini AI generated passage
const geminiDescVi = 'Đề thi Passage 3 sinh bởi Gemini AI theo chuẩn Cambridge Academic.';
const geminiDescEn = formatTestDescription(geminiDescVi, true, {});
assert(
  geminiDescEn === 'Passage 3 reading test generated by Gemini AI following Cambridge Academic standard.',
  'formatTestDescription translates Gemini AI generated passage description accurately'
);

console.log(`\n🎉 STEP 106 PASSED: ${passed}/${total} tests passed!`);
