/**
 * testLocalizationHelper.js
 * Centralized bilingual formatter for Cambridge, AI, Community, and Custom test titles & descriptions.
 */

/**
 * Translates Vietnamese tags/prefixes in test titles to English when isEn is true.
 * @param {string} title 
 * @param {boolean} isEn 
 * @returns {string}
 */
export function formatTestTitle(title, isEn) {
  if (!title || !isEn) return title || '';
  return title
    .replace(/\[AI Cộng Đồng\]/g, '[Community AI]')
    .replace(/\[Cộng Đồng\]/g, '[Community]')
    .replace(/\[Báo chí - P(\d+)\]/g, '[Press - P$1]')
    .replace(/\[Báo chí\]/g, '[Press]')
    .replace(/\[Đề Ghép\]/g, '[Assembled Test]');
}

/**
 * Translates Vietnamese test descriptions to English when isEn is true.
 * Handles official Cambridge reading/listening tests, AI-generated tests, and custom builder tests.
 * @param {string} desc 
 * @param {boolean} isEn 
 * @param {object} test 
 * @returns {string}
 */
export function formatTestDescription(desc, isEn, test = {}) {
  if (!isEn) return desc || '';
  if (!desc) {
    return 'Standard academic IELTS test with multiple-choice and completion questions.';
  }

  // 1. Cambridge Reading full test: "Bộ đề thi thử IELTS Reading chuẩn khảo thí Cambridge X (Mới nhất) gồm đầy đủ 3 bài đọc học thuật với 40 câu hỏi..."
  const camMatch = desc.match(/Cambridge\s*(\d+)/i) || (test.cambridgeBook ? [null, String(test.cambridgeBook)] : null);
  const isLatest = desc.includes('Mới nhất') || desc.includes('mới nhất');

  if (desc.includes('IELTS Reading chuẩn khảo thí Cambridge') || (desc.includes('chuẩn khảo thí Cambridge') && (desc.includes('Reading') || test.id?.includes('reading')))) {
    const bookNum = camMatch ? camMatch[1] : (test.cambridgeBook || '');
    return `Official Cambridge ${bookNum} IELTS Reading practice test${isLatest ? ' (Latest)' : ''} with 3 full academic passages, 40 questions, and a 60-minute time limit.`;
  }

  // 2. Cambridge 15 / Authentic format: "Bộ đề thi thử chuẩn Cambridge Academic gồm 3 bài đọc với đầy đủ 40 câu hỏi, thời gian làm bài 60 phút."
  if (desc.includes('chuẩn Cambridge Academic gồm 3 bài đọc') || desc.includes('Bộ đề thi thử chuẩn Cambridge Academic')) {
    return 'Authentic Cambridge Academic practice test featuring 3 complete passages, 40 questions, and a 60-minute duration.';
  }

  // 3. AI Community test: "Đề thi đọc học thuật do AI thiết kế chuẩn Cambridge Academic: Cơ chế pin mặt trời Perovskite, hiệu suất chuyển đổi quang năng và bài toán kinh tế."
  if (desc.includes('Đề thi đọc học thuật do AI thiết kế')) {
    return 'Academic reading test generated by AI under Cambridge Academic standards: Perovskite solar cell mechanics, energy conversion efficiency, and economic viability.';
  }

  // 4. Ingested article test: "Đề thi Passage X trích xuất từ bài báo theo chuẩn Cambridge Academic."
  const ingestMatch = desc.match(/Passage\s*(\d+)\s*trích xuất từ bài báo/i);
  if (ingestMatch) {
    return `Passage ${ingestMatch[1]} reading test extracted from real-world press article under Cambridge Academic standards.`;
  }

  // 5. AI generated single passage: "Đề thi Passage X sinh bởi AI theo chuẩn Cambridge Academic."
  const aiGenMatch = desc.match(/Passage\s*(\d+)\s*sinh bởi AI/i);
  if (aiGenMatch) {
    return `Passage ${aiGenMatch[1]} reading test generated by AI under Cambridge Academic standards.`;
  }

  // 6. Assembled 3-passage test: "Bộ đề thi thử 3 Passages tự lắp ghép từ ngân hàng đề (X + Y + Z). Chuẩn thi thật 60 phút."
  if (desc.includes('Bộ đề thi thử 3 Passages tự lắp ghép')) {
    const passagesPart = desc.match(/\((.*?)\)/);
    const passagesList = passagesPart ? ` (${passagesPart[1]})` : '';
    return `Custom 3-Passage mock exam assembled from the test bank${passagesList}. Cambridge 60-minute standard.`;
  }

  // 7. Cambridge Listening full test: "Bộ đề thi thử IELTS Listening chuẩn khảo thí Cambridge X..."
  if (desc.includes('IELTS Listening chuẩn khảo thí Cambridge') || (desc.includes('chuẩn khảo thí Cambridge') && (desc.includes('Listening') || test.id?.includes('listening')))) {
    const bookNum = camMatch ? camMatch[1] : (test.cambridgeBook || '');
    return `Official Cambridge ${bookNum} IELTS Listening mock test${isLatest ? ' (Latest)' : ''} with 4 complete parts (Part 1–4), 40 questions, 30-min audio, and 2-min review time.`;
  }

  return desc;
}
